Class {
	#name : #RABaseVisitor,
	#superclass : #Object,
	#category : #'ReflexiveAST-core'
}

{ #category : #visiting }
RABaseVisitor >> visitArgumentDefinition: argumentDefinitionNode [

]

{ #category : #visiting }
RABaseVisitor >> visitArgumentUse: argumentUse [
]

{ #category : #visiting }
RABaseVisitor >> visitArray: array [
]

{ #category : #visiting }
RABaseVisitor >> visitAssignment: assignment [
]

{ #category : #visiting }
RABaseVisitor >> visitBinaryMessageSend: binaryMessageSend [
]

{ #category : #visiting }
RABaseVisitor >> visitBlock: block [
]

{ #category : #visiting }
RABaseVisitor >> visitBoolean: boolean [
]

{ #category : #visiting }
RABaseVisitor >> visitClass: aClassNode [

]

{ #category : #visiting }
RABaseVisitor >> visitComment: comment [
]

{ #category : #visiting }
RABaseVisitor >> visitDynamicArray: dynamicArray [
]

{ #category : #visiting }
RABaseVisitor >> visitInstVar: instVar [
]

{ #category : #visiting }
RABaseVisitor >> visitInstVarUse: instVarUse [
]

{ #category : #visiting }
RABaseVisitor >> visitKeyword: keyword [
]

{ #category : #visiting }
RABaseVisitor >> visitKeywordDefinition: keywordDefinition [
]

{ #category : #visiting }
RABaseVisitor >> visitMessageSend: messageSend [
]

{ #category : #visiting }
RABaseVisitor >> visitMethod: method [
]

{ #category : #visiting }
RABaseVisitor >> visitMethodSignature: methodSignature [
]

{ #category : #visiting }
RABaseVisitor >> visitNumber: number [
]

{ #category : #visiting }
RABaseVisitor >> visitPseudoVariable: aVisitor [
]

{ #category : #visiting }
RABaseVisitor >> visitReturn: return [
]

{ #category : #visiting }
RABaseVisitor >> visitSelector: selector [
]

{ #category : #visiting }
RABaseVisitor >> visitString: str [
]

{ #category : #visiting }
RABaseVisitor >> visitTempDefinition: tempDefinition [
]

{ #category : #visiting }
RABaseVisitor >> visitTempUse: tempUse [
]
